"""empty message

Revision ID: 896afd56324a
Revises: faef9a1fd6e5
Create Date: 2020-08-31 22:05:44.696937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896afd56324a'
down_revision = 'faef9a1fd6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    # ### end Alembic commands ###
